[package]
name = "anki_streak_fixer"
version = "0.4.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.1", features = ["load_extension", "collation"] }
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] }
shellexpand = "3.1.0"
unicase = "2.6.0"

[dev-dependencies]
